export const CARD_ADDED_EVENT = "CARD_ADDED_EVENT";
export const CARD_DELETED_EVENT = "CARD_DELETED_EVENT";
export const CARD_UPDATED_EVENT = "CARD_UPDATED_EVENT";
export const CARD_ORDER_EVENT = "CARD_ORDER_EVENT";

export const LIST_ADDED_EVENT = "LIST_ADDED_EVENT";
export const LIST_DELETED_EVENT = "LIST_DELETED_EVENT";

export const BOARD_ADDED_EVENT = "BOARD_ADDED_EVENT";
export const BOARD_DELETED_EVENT = "BOARD_DELETED_EVENT";
export const BOARD_UPDATED_EVENT = "BOARD_UPDATED_EVENT";
