export const CARD_ADDED_EVENT = "CARD_ADDED_EVENT";
export const CARD_DELETED_EVENT = "CARD_DELETED_EVENT";
export const CARD_UPDATED_EVENT = "CARD_UPDATED_EVENT";

export const LIST_ADDED_EVENT = "LIST_ADDED_EVENT";
export const LIST_DELETED_EVENT = "LIST_DELETED_EVENT";
