mutation addCard ($title:String!,$owner_id:ID!,$list_id:ID!,$order:Int!) {
    addCard(input:{title:$title,owner_id:$owner_id,list_id:$list_id,order:$order}){
        id
        title
        order
        owner{
            id
        }
    }
}
